name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

env:
  PYTHON_VERSION: "3.10"
  NODE_VERSION: 14
  NODE_OPTIONS: --max_old_space_size=6144

permissions:
  actions: none

jobs:
  nightly:
    name: Nightly
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: |
          pip install build
          yarn install

      - name: Download Translations
        run: ./script/translations_download
        env:
          LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}

      - name: Bump version
        run: script/version_bump.js nightly

      - name: Build nightly Python wheels
        run: |
          yarn install

          script/build_frontend

          rm -rf dist home_assistant_frontend.egg-info
          python3 -m build

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/
          if-no-files-found: error
